{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix # Generated by nixos-generate-config
    ../../modules/core.nix
    ../../modules/users.nix
    ../../modules/networking.nix
    ../../modules/desktop.nix
    ../../modules/audio.nix
    ../../modules/services.nix
    ../../modules/packages.nix
    ../../modules/gaming.nix
    ../../modules/hardware/nvidia.nix
  ];

  networking.hostName = "gavin-pc";

  # CachyOS Kernel (via chaotic-nyx)
  boot.kernelPackages = pkgs.linuxPackages_cachyos;

  # Bootloader: NixOS doesn't have an official Limine module in nixpkgs yet.
  # If you strictly want Limine, you need a 3rd party flake (like nixos-limine).
  # For now, systemd-boot is the safest, most robust fallback for EFI + Btrfs.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Snapper Btrfs integration
  services.snapper.configs = {
    home = {
      SUBVOLUME = "/home";
      ALLOW_USERS = [ "gav" ];
      TIMELINE_CREATE = true;
      TIMELINE_CLEANUP = true;
    };
  };

  # Hardware
  hardware.openrazer.enable = true;
  hardware.openrazer.users = [ "gav" ];
  
  services.sunshine = {
    enable = true;
    openFirewall = true;
    capSysAdmin = true;
  };

  # Btrfs Assistant & Snapper GUI
  environment.systemPackages = with pkgs; [
    btrfs-assistant
    snapper
  ];
{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ../../modules/core.nix
    ../../modules/users.nix
    ../../modules/networking.nix
    ../../modules/desktop.nix
    ../../modules/audio.nix
    ../../modules/services.nix
    ../../modules/packages.nix
    ../../modules/gaming.nix
    ../../modules/hardware/nvidia.nix
  ];

  networking.hostName = "gavin-pc";

  boot.kernelPackages = pkgs.linuxPackages_cachyos;
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  services.snapper.configs = {
    home = {
      SUBVOLUME = "/home";
      ALLOW_USERS = [ "gav" ];
      TIMELINE_CREATE = true;
      TIMELINE_CLEANUP = true;
    };
  };

  hardware.openrazer.enable = true;
  hardware.openrazer.users = [ "gav" ];
  
  services.sunshine = {
    enable = true;
    openFirewall = true;
    capSysAdmin = true;
  };

  environment.systemPackages = with pkgs; [
    btrfs-assistant
    snapper
  ];
}}
