{ config, pkgs, inputs, lib, ... }:

let
  # GambinoSupremo/dotfiles with Arch-specific bits patched for NixOS.
  # Files that Noctalia regenerates at runtime (mango/noctalia.conf,
  # niri/noctalia.kdl, ghostty/themes/noctalia) are removed here so they are
  # never deployed as read-only store symlinks; they are seeded as writable
  # copies by home.activation.seedNoctaliaTemplates below.
  dotfiles = pkgs.runCommandLocal "dotfiles-patched" { } ''
    mkdir -p $out
    for d in mango niri hypr ghostty; do
      cp -r ${inputs.dotfiles}/$d $out/$d
    done
    chmod -R u+w $out

    # mango: portals are dbus-activated on NixOS (no /usr/lib path), and
    # Noctalia v5 runs as a systemd user service so logs land in the journal.
    sed -i \
      -e 's|^exec-once=/usr/lib/xdg-desktop-portal-wlr$|exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP|' \
      -e "s|^exec-once=qs -c noctalia-shell$|exec-once=sh -c 'systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP; systemctl --user start noctalia.service'|" \
      $out/mango/autostart.conf
    sed -i 's|/usr/bin/ghostty|ghostty|g' $out/mango/bind.conf

    # niri: noctalia.service is started by graphical-session.target under
    # niri-session, and the unconditional trailing include of the
    # runtime-generated noctalia.kdl is dropped (the optional include stays).
    sed -i \
      -e '/^spawn-at-startup "qs" "-c" "noctalia-shell"$/d' \
      -e '/^include "\.\/noctalia\.kdl"$/d' \
      $out/niri/config.kdl

    # hypr: the .lua config is loaded by an Arch-only plugin, so the effective
    # config is just hyprland.conf (whose noctalia source is already optional).
    # Append a minimal usable fallback so the session is never a dead end.
    sed -i 's|/usr/bin/ghostty|ghostty|g' $out/hypr/workspaces.lua
    cat >> $out/hypr/hyprland.conf <<'EOF'

# ── NixOS additions ─────────────────────────────────────────────────────────
# The lua-based config in this directory needs an Arch-only plugin; keep a
# minimal fallback so the Hyprland session is usable on NixOS.
monitor = , preferred, auto, 1
exec-once = systemctl --user start noctalia.service
bind = SUPER, Return, exec, ghostty
bind = SUPER, Q, killactive
bind = SUPER SHIFT, E, exit
EOF

    # ghostty: drop the Arch zsh/pokemon-colorscripts command; the login
    # shell on NixOS is fish.
    sed -i '/^command = /d' $out/ghostty/config

    # Runtime-generated by Noctalia — never deploy read-only (seeded instead)
    rm $out/mango/noctalia.conf
    rm $out/niri/noctalia.kdl
    rm $out/ghostty/themes/noctalia
  '';
in
{
  imports = [
    # Noctalia home-manager module — provides programs.noctalia.*
    inputs.noctalia.homeModules.default
  ];

  home.username      = "gav";
  home.homeDirectory = "/home/gav";
  home.stateVersion  = "25.05";
  programs.home-manager.enable = true;

  # ── Noctalia shell (v5) ──────────────────────────────────────────────────────
  # The flake module's option namespace is programs.noctalia (NOT
  # programs.noctalia-shell as the wiki says) and the binary is `noctalia`.
  # systemd.enable creates noctalia.service, WantedBy graphical-session.target:
  #   - niri:     niri-session starts graphical-session.target → auto-start
  #   - hyprland: hyprland-session.target pulls graphical-session.target
  #   - mango:    autostart.conf starts noctalia.service explicitly (patched above)
  # Logs: journalctl --user -u noctalia.service
  programs.noctalia = {
    enable         = true;
    systemd.enable = true;

    # v5 settings are TOML (see example.toml in the noctalia repo). Keep this
    # minimal — everything else is managed at runtime via the settings UI,
    # which Noctalia persists itself (those files stay writable).
    settings = {
      shell.telemetry_enabled = false;
      theme.mode = "dark";
      wallpaper = {
        enabled   = true;
        directory = "~/Pictures/backgrounds";
        automation = {
          enabled          = true;
          interval_minutes = 45;     # was randomIntervalSec = 2700
          order            = "random";
        };
      };
    };
  };

  # ── Dotfiles (GambinoSupremo/dotfiles) ───────────────────────────────────────
  # recursive = true links each file individually so the directories stay
  # writable for runtime-generated files; force = true overwrites leftovers
  # from earlier non-declarative deployments instead of aborting.
  xdg.configFile = {
    "mango"   = { source = "${dotfiles}/mango";   recursive = true; force = true; };
    "niri"    = { source = "${dotfiles}/niri";    recursive = true; force = true; };
    "hypr"    = { source = "${dotfiles}/hypr";    recursive = true; force = true; };
    "ghostty" = { source = "${dotfiles}/ghostty"; recursive = true; force = true; };
  };

  # Seed Noctalia's runtime template files once, as writable copies, so the
  # first boot has colors and mango's `source = .../noctalia.conf` resolves.
  # Noctalia overwrites them whenever the theme changes.
  home.activation.seedNoctaliaTemplates = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    seedNoctalia() {
      if [ ! -e "$2" ]; then
        run mkdir -p "$(dirname "$2")"
        run cp "$1" "$2"
        run chmod u+w "$2"
      fi
    }
    seedNoctalia ${inputs.dotfiles}/mango/noctalia.conf     ${config.xdg.configHome}/mango/noctalia.conf
    seedNoctalia ${inputs.dotfiles}/niri/noctalia.kdl       ${config.xdg.configHome}/niri/noctalia.kdl
    seedNoctalia ${inputs.dotfiles}/ghostty/themes/noctalia ${config.xdg.configHome}/ghostty/themes/noctalia
  '';

  # ── GTK / Qt theming ─────────────────────────────────────────────────────────
  gtk = {
    enable = true;
    theme = {
      name    = "adw-gtk3-dark";
      package = pkgs.adw-gtk3;
    };
    iconTheme = {
      name    = "Papirus-Dark";
      package = pkgs.papirus-icon-theme;
    };
  };

  home.pointerCursor = {
    gtk.enable = true;
    name       = "Bibata-Modern-Ice";
    package    = pkgs.bibata-cursors;
    size       = 24;
  };

  qt = {
    enable = true;
    platformTheme.name = "qtct";   # matches QT_QPA_PLATFORMTHEME=qt6ct in mango/env.conf
    style = {
      name    = "kvantum";
      package = pkgs.kdePackages.qtstyleplugin-kvantum;
    };
  };

  # ── Fish ─────────────────────────────────────────────────────────────────────
  programs.fish = {
    enable = true;
    interactiveShellInit = ''
      set fish_greeting ""
      # pokemon-colorscripts on launch
      # pokemon-colorscripts --no-title -r 2>/dev/null || true
    '';
    shellAliases = {
      ls   = "eza --icons --group-directories-first";
      la   = "eza -la --icons --group-directories-first";
      ll   = "eza -l --icons --group-directories-first";
      tree = "eza --tree --icons --group-directories-first";
      cat  = "bat --style=plain";
      grep = "rg";
    };
  };

  # ── Starship ──────────────────────────────────────────────────────────────────
  programs.starship = {
    enable                = true;
    enableFishIntegration = true;
    # settings = builtins.fromTOML (builtins.readFile ./starship.toml);
  };

  # ── fzf ───────────────────────────────────────────────────────────────────────
  programs.fzf = {
    enable = true;
    # Fish integration disabled — it binds Ctrl+T which conflicts with
    # Fish's built-in transpose-chars. Handled manually: bind ctrl-t fzf-file-widget
    enableFishIntegration = false;
  };

  # ── zoxide ────────────────────────────────────────────────────────────────────
  programs.zoxide = {
    enable                = true;
    enableFishIntegration = true;
  };

  # ── bat ───────────────────────────────────────────────────────────────────────
  programs.bat = {
    enable = true;
    config = {
      theme = "base16";
      style = "plain";
    };
  };

  # ── Git ───────────────────────────────────────────────────────────────────────
  programs.git = {
    enable      = true;
    userName    = "Gavin";
    userEmail   = "";
    extraConfig = {
      init.defaultBranch   = "main";
      push.autoSetupRemote = true;
    };
  };

  # ── Neovim ────────────────────────────────────────────────────────────────────
  # LazyVim manages plugins via lazy.nvim and writes lazy-lock.json into
  # ~/.config/nvim, so the nvim dotfiles are NOT deployed declaratively —
  # clone/stow them manually, or migrate to programs.neovim.plugins later.
  programs.neovim = {
    enable        = true;
    defaultEditor = true;
    vimAlias      = true;
  };

  # ── OBS Studio plugins ────────────────────────────────────────────────────────
  # programs.obs-studio = {
  #   enable  = true;
  #   plugins = with pkgs.obs-studio-plugins; [
  #     obs-vaapi
  #     obs-vkcapture
  #   ];
  # };
}
